Models/ModelOuvrage.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercice1_APP_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelOuvrageContainer : DbContext
    {
        public ModelOuvrageContainer()
            : base("name=ModelOuvrageContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ouvrage> OuvrageSet { get; set; }
    }
}

Models/ModelOuvrage.Designer.cs
// T4 code generation is enabled for model 'C:\Users\user\Desktop\EFM_ASP_TDI203A_Mazzouz_Chaimae\Exercice1_APP_MVC\Models\ModelOuvrage.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/ModelOuvrage.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Models/Ouvrage.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercice1_APP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvrage
    {
        public int Num_Ouv { get; set; }
        public string Titre_Ouv { get; set; }
        public double PU { get; set; }
        public int Nb_Exp { get; set; }
    }
}

Controllers/OuvragesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Exercice1_APP_MVC.Models;

namespace Exercice1_APP_MVC.Controllers
{
    public class OuvragesController : Controller
    {
        private ModelOuvrageContainer db = new ModelOuvrageContainer();

        // GET: Ouvrages
        public ActionResult Index()
        {
            return View(db.OuvrageSet.ToList());
        }

        // GET: Ouvrages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ouvrage ouvrage = db.OuvrageSet.Find(id);
            if (ouvrage == null)
            {
                return HttpNotFound();
            }
            return View(ouvrage);
        }

        // GET: Ouvrages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ouvrages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Num_Ouv,Titre_Ouv,PU,Nb_Exp")] Ouvrage ouvrage)
        {
            if (ModelState.IsValid)
            {
                db.OuvrageSet.Add(ouvrage);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ouvrage);
        }

        // GET: Ouvrages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ouvrage ouvrage = db.OuvrageSet.Find(id);
            if (ouvrage == null)
            {
                return HttpNotFound();
            }
            return View(ouvrage);
        }

        // POST: Ouvrages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Num_Ouv,Titre_Ouv,PU,Nb_Exp")] Ouvrage ouvrage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ouvrage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ouvrage);
        }

        // GET: Ouvrages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ouvrage ouvrage = db.OuvrageSet.Find(id);
            if (ouvrage == null)
            {
                return HttpNotFound();
            }
            return View(ouvrage);
        }

        // POST: Ouvrages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ouvrage ouvrage = db.OuvrageSet.Find(id);
            db.OuvrageSet.Remove(ouvrage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Ouvrages/Create.cshtml
@model Exercice1_APP_MVC.Models.Ouvrage

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ouvrage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titre_Ouv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre_Ouv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre_Ouv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nb_Exp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nb_Exp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nb_Exp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Ouvrages/Delete.cshtml
@model Exercice1_APP_MVC.Models.Ouvrage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ouvrage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre_Ouv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre_Ouv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nb_Exp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nb_Exp)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Ouvrages/Details.cshtml
@model Exercice1_APP_MVC.Models.Ouvrage

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ouvrage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre_Ouv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre_Ouv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nb_Exp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nb_Exp)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Num_Ouv }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Ouvrages/Edit.cshtml
@model Exercice1_APP_MVC.Models.Ouvrage

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ouvrage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Num_Ouv)

        <div class="form-group">
            @Html.LabelFor(model => model.Titre_Ouv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre_Ouv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre_Ouv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nb_Exp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nb_Exp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nb_Exp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Ouvrages/Index.cshtml
@model IEnumerable<Exercice1_APP_MVC.Models.Ouvrage>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titre_Ouv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PU)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nb_Exp)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titre_Ouv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PU)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nb_Exp)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Num_Ouv }) |
            @Html.ActionLink("Details", "Details", new { id=item.Num_Ouv }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Num_Ouv })
        </td>
    </tr>
}

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gestion Ouvrage", "Index", "Ouvrages", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ouvrages", "Index", "Ouvrages")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>